# This is a basic workflow to help you get started with Actions

name: Builder

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  my_job:
    name: deploy
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3
        
      - name: Build Glad
        run: msbuild Engine/vendor/Glad /p:Configuration=Debug /p:Platform="x64"
        
      - name: Build GLFW
        run: msbuild Engine/vendor/GLFW /p:Configuration=Debug /p:Platform="x64"
        
      - name: Build ImGui
        run: msbuild Engine/vendor/ImGui /p:Configuration=Debug /p:Platform="x64"
        
      - name: Build Engine
        run: msbuild Engine/Engine /p:Configuration=Debug /p:Platform="x64"
